# Generated by Django 2.2 on 2019-05-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_auto_20190506_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_id'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
