# Generated by Django 2.2 on 2019-05-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20190506_1219'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_info',
        ),
    ]
